parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
<<<<<<< HEAD
    database_name: freche1u_devspe2
    database_user: freche1u_appli
    database_password: devspe
=======
    database_name: test
    database_user: admin
    database_password: 
>>>>>>> 7b160890c23327ebb462a8a50dbf4f283bf22bb5
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: ThisTokenIsNotSoSecretChangeIt
    app_webmaster: Foret Gael , Regnault Gerome , Debize Michael , Sardo Alexandre , Freche Banjamin