acme_security:
    resource: "@AcmeSecurityBundle/Resources/config/routing.yml"
    prefix:   /
sujet2_dev_spe:
    resource: "@Sujet2DevSpeBundle/Resources/config/routing.yml"
<<<<<<< HEAD
    prefix:   
login:
    path:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout
=======
    prefix:
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
>>>>>>> 39153aa81a69b5cfddb33c90bc1dc53cc81bf1c5
