<?php

namespace Sujet2\DevSpeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Lieu_DepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lieu_DepartRepository extends EntityRepository
{
}
