<?php

namespace Sujet2\DevSpeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Type_PtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_PtsRepository extends EntityRepository
{
}
