<?php

namespace Sujet2\DevSpeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoeuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoeuxRepository extends EntityRepository
{
}
