# src/Sujet2/DevSpeBundle/Resources/config/routing.yml
sujet2devspe_acceuil:
    path: /acceuil
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:accueil } 
sujet2devspe_phase2:
    path: /Creation/phase2
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase2 }
sujet2devspe_phase1:
    path: /Creation/phase1
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase1 }
sujet2devspe_phase3:
    path: /Creation/phase3
<<<<<<< HEAD
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase3 }
sujet2devspe_phase4:
    path: /Creation/phase4
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase4 }
=======
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase3 }	
>>>>>>> 1044f5c55a9e9ccbbb9e2b616ae8eebea2513595
sujet2devspe_acceuilenseignant:
    path: /acceuilens
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:accueilens }
sujet2devspe_profilenseignant:
    path: /profilens
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:profilens }
sujet2devspe_profilenseignant:
    path: /profiladr
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:adresse_enseignant }
sujet2devspe_acceuilgestionnaire:
    path: /acceuilges
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:accueilges }

