# src/Sujet2/DevSpeBundle/Resources/config/routing.yml
sujet2devspe_acceuil:
    path: /acceuil
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:accueil } 
sujet2devspe_phase2:
    path: /Creation/phase2
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase2 }
sujet2devspe_phase1:
    path: /Creation/phase1
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase1 }
sujet2devspe_phase3:
    path: /Creation/phase3
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase3 }
sujet2devspe_phase4:
    path: /Creation/phase4
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase4 }
sujet2devspe_acceuilenseignant:
    path: /acceuilens
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:accueilens }
sujet2devspe_enseignant:
    path: /profilens
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:profilens }
sujet2devspe_adresseenseignant:
    path: /profiladr
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:adresse_enseignant }
sujet2devspe_acceuilgestionnaire:
    path: /acceuilges
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:accueilges }
sujet2devspe_phase5:
    path: /Creation/phase5
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:phase5 }
sujet2_devspeannullersession:
    path: /Creation/annuler
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:annulersession }
sujet2_devspevalidersession:
    path: /Creation/valider
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:validersession }
sujet2redirect:
    path: /choix
    defaults: { _controller: AcmeSecurityBundle:Security:choix }
sujet2devspe_homepage:
    path: /
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:index }
sujet2devspe_visualisersession:
    path: /visualiser
    defaults: { _controller: Sujet2DevSpeBundle:DevSpe:visualisersession }
sujet2devpspe_uploadcsv:
   path: /csv
   defaults: { _controller: Sujet2DevSpeBundle:Moulinette:choixfichier }
