<?php

namespace Proxies\__CG__\Sujet2\DevSpeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Parametre extends \Sujet2\DevSpeBundle\Entity\Parametre implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDistMax($distMax)
    {
        $this->__load();
        return parent::setDistMax($distMax);
    }

    public function getDistMax()
    {
        $this->__load();
        return parent::getDistMax();
    }

    public function setTolerance($tolerance)
    {
        $this->__load();
        return parent::setTolerance($tolerance);
    }

    public function getTolerance()
    {
        $this->__load();
        return parent::getTolerance();
    }

    public function setLibelle($libelle)
    {
        $this->__load();
        return parent::setLibelle($libelle);
    }

    public function getLibelle()
    {
        $this->__load();
        return parent::getLibelle();
    }

    public function addContrainte(\Sujet2\DevSpeBundle\Entity\Lot $contrainte)
    {
        $this->__load();
        return parent::addContrainte($contrainte);
    }

    public function removeContrainte(\Sujet2\DevSpeBundle\Entity\Contrainte $contrainte)
    {
        $this->__load();
        return parent::removeContrainte($contrainte);
    }

    public function getContraintes()
    {
        $this->__load();
        return parent::getContraintes();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'distMax', 'tolerance', 'libelle', 'contraintes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}