<?php

namespace Proxies\__CG__\Sujet2\DevSpeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Entreprise extends \Sujet2\DevSpeBundle\Entity\Entreprise implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEntRs($entRs)
    {
        $this->__load();
        return parent::setEntRs($entRs);
    }

    public function getEntRs()
    {
        $this->__load();
        return parent::getEntRs();
    }

    public function setEntAdr($entAdr)
    {
        $this->__load();
        return parent::setEntAdr($entAdr);
    }

    public function getEntAdr()
    {
        $this->__load();
        return parent::getEntAdr();
    }

    public function setEntCp($entCp)
    {
        $this->__load();
        return parent::setEntCp($entCp);
    }

    public function getEntCp()
    {
        $this->__load();
        return parent::getEntCp();
    }

    public function setEntVille($entVille)
    {
        $this->__load();
        return parent::setEntVille($entVille);
    }

    public function getEntVille()
    {
        $this->__load();
        return parent::getEntVille();
    }

    public function setEntPays($entPays)
    {
        $this->__load();
        return parent::setEntPays($entPays);
    }

    public function getEntPays()
    {
        $this->__load();
        return parent::getEntPays();
    }

    public function setEntTel($entTel)
    {
        $this->__load();
        return parent::setEntTel($entTel);
    }

    public function getEntTel()
    {
        $this->__load();
        return parent::getEntTel();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'entRs', 'entAdr', 'entCp', 'entVille', 'entPays', 'entTel');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}