<?php

namespace Proxies\__CG__\Sujet2\DevSpeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Enseignant extends \Sujet2\DevSpeBundle\Entity\Enseignant implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEnsCiv($ensCiv)
    {
        $this->__load();
        return parent::setEnsCiv($ensCiv);
    }

    public function getEnsCiv()
    {
        $this->__load();
        return parent::getEnsCiv();
    }

    public function setEnsNom($ensNom)
    {
        $this->__load();
        return parent::setEnsNom($ensNom);
    }

    public function getEnsNom()
    {
        $this->__load();
        return parent::getEnsNom();
    }

    public function setEnsPrenom($ensPrenom)
    {
        $this->__load();
        return parent::setEnsPrenom($ensPrenom);
    }

    public function getEnsPrenom()
    {
        $this->__load();
        return parent::getEnsPrenom();
    }

    public function setEnsAdresse($ensAdresse)
    {
        $this->__load();
        return parent::setEnsAdresse($ensAdresse);
    }

    public function getEnsAdresse()
    {
        $this->__load();
        return parent::getEnsAdresse();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'ensCiv', 'ensNom', 'ensPrenom', 'ensAdresse');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}